function [fig2]=figure_plot(Ksections,delp)
    fig1=figure(1);
    subplot(3,3,1)
    plot(delp,Ksections(1:6:(length(delp))*6,1),'-k','Linewidth',2)
    title('S_{11}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,2)
    plot(delp,Ksections(1:6:(length(delp))*6,2),'-k','Linewidth',2)
    title('S_{12}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,3)
    plot(delp,Ksections(1:6:(length(delp))*6,3),'-k','Linewidth',2)
    title('S_{13}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,4)
    plot(delp,Ksections(1:6:(length(delp))*6,4),'-k','Linewidth',2)
    title('S_{14}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,5)
    plot(delp,Ksections(1:6:(length(delp))*6,6),'-k','Linewidth',2)
    title('S_{16}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,6)
    plot(delp,Ksections(2:6:(length(delp))*6+1,2),'-k','Linewidth',2)
    title('S_{22}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,7)
    plot(delp,Ksections(2:6:(length(delp))*6+1,3),'-k','Linewidth',2)
    title('S_{23}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,8)
    plot(delp,Ksections(2:6:(length(delp))*6+1,4),'-k','Linewidth',2)
    title('S_{24}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,9)
    plot(delp,Ksections(2:6:(length(delp))*6+1,6),'-k','Linewidth',2)
    title('S_{26}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    han=axes(fig1,'visible','off'); 
    han.Title.Visible='off';
    han.XLabel.Visible='on';
    han.YLabel.Visible='off';
%     ylabel(han,'yourYLabel');
    xlabel(han,'Delamination ratio(l_b/b_f)','Fontsize',14');
%     title(han,'yourTitle');
    fig2=figure(2);
    subplot(3,3,1)
    plot(delp,Ksections(3:6:(length(delp))*6+2,3),'-k','Linewidth',2)
    title('S_{33}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,2)
    plot(delp,Ksections(3:6:(length(delp))*6+2,4),'-k','Linewidth',2)
    title('S_{34}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,3)
    plot(delp,Ksections(3:6:(length(delp))*6+2,6),'-k','Linewidth',2)
    title('S_{36}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,4)
    plot(delp,Ksections(4:6:(length(delp))*6+3,4),'-k','Linewidth',2)
    title('S_{44}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,5)
    plot(delp,Ksections(4:6:(length(delp))*6+3,6),'-k','Linewidth',2)
    title('S_{46}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    subplot(3,3,6)
    plot(delp,Ksections(6:6:(length(delp))*6+5,6),'-k','Linewidth',2);
    title('S_{66}','Fontsize',12)
    ax=gca;
    ax.FontWeight='bold';
    han=axes(fig2,'visible','off'); 
    han.Title.Visible='off';
    han.XLabel.Visible='on';
    han.YLabel.Visible='off';
%     ylabel(han,'yourYLabel');
    xlabel(han,'Delamination ratio (l_b/b_f)','Fontsize',14','Position',[0.5,0.31]);
%     title(han,'yourTitle');
end
    